app/models.py
class News:
    
    def __init__(self,source,title, content, description, urlToImage, publishedAt,url,author):
        self.source = source
        self.title = title
        self.content = content
        self.description = description
        self.urlToImage = urlToImage
        self.publishedAt = publishedAt
        self.url = url
        self.author = author
        
        
class Source:
    
    def __init__(self,id,name,description,url,category,language,country):
        self.id = id
        self.name = name
        self.description = description
        self.url = url
        self.category = category
        self.language = language
        self.country =country
        

app/forms.py
from flask_wtf import FlaskForm
from  wtforms import  StringField, SubmitField
from  wtforms.validators import  Required

class SearchForm(FlaskForm):
    searchTerm = StringField('search',validators=[Required()])
    
    submit = SubmitField('Search')

app/__init__.py
from flask import Flask

def create_app(config_name):
    app = Flask(__name__)
    
    
    from .views import views
    
    app.register_blueprint(views, url_prefix ='/')
    return app

app/views.py
from flask import Blueprint,render_template,redirect,url_for,request
from .requests import  all_news, headlines, search_category, search_News,source_news
from .forms import  SearchForm

views = Blueprint('views', __name__)

@views.route('home/All-news',  methods = ['GET', 'POST'])
def all_News():
    allnews = all_news()
    form = SearchForm()
    if request.method == 'POST' and form.validate_on_submit():
        searchTerm = form.searchTerm.data
        return redirect(url_for('views.searchNews', searchTerm =searchTerm))
    return render_template('All-news.html', allnews = allnews,form=form)

@views.route('home/<sourceChannel>',  methods = ['GET', 'POST'])
def channel_News(sourceChannel):
    allchannelnews = source_news(sourceChannel)
    form = SearchForm()
    if request.method == 'POST' and form.validate_on_submit():
        searchTerm = form.searchTerm.data
        return redirect(url_for('views.searchNews', searchTerm =searchTerm))
    return render_template('All-news.html', allnews = allchannelnews,form=form)


@views.route('/' , methods = ['GET', 'POST'])
@views.route('/home' , methods = ['GET', 'POST'])
def headline_articles():
    headlinesNews = headlines() 
    form = SearchForm()
    if request.method == 'POST' and form.validate_on_submit():
        searchTerm = form.searchTerm.data
        return redirect(url_for('views.searchNews', searchTerm =searchTerm))
    return render_template('home.html', headlinesNews = headlinesNews,form = form)



@views.route('home/All-news/<category>', methods = ['GET', 'POST'])
def categoryNews(category):
    category_news = search_category(category)
    form = SearchForm()
    if request.method == 'POST' and form.validate_on_submit():
        searchTerm = form.searchTerm.data
        return redirect(url_for('views.searchNews', searchTerm =searchTerm))
    return render_template('category.html', category_news = category_news, form=form, category = category)


@views.route('home/search/<searchTerm>', methods = ['GET','POST'])
def searchNews(searchTerm):
    found_news = search_News(searchTerm)
    form = SearchForm()
    if found_news:
        if request.method == 'POST' and form.validate_on_submit():
            searchTerm = form.searchTerm.data
            return redirect(url_for('views.searchNews', searchTerm =searchTerm, form = form))
        
        return render_template('search.html', found_news = found_news, form=form, searchTerm=searchTerm)
    else:
        return render_template('error.html', form=form)


@views.errorhandler(404)
def not_found(error):
    return render_template('notFound.html', error =error)

app/templates/All-news.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}

{% block title%}All News{%endblock%}
{% block content%}

 {{macro.displayNews(allnews)}}
{% endblock%}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'styles.css') }}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Great+Vibes&family=Poppins:wght@400&display=swap" rel="stylesheet">
    <title>
        {% block title%}Home{%endblock%}
    </title>
</head>
<body>
    {% include 'navbar.html'%}
    <div class="container-fluid p-3 m-0">
    {% include 'form.html'%}
        <div class="row">
            <div class="col-md-2">
                <div class="position-fixed">
                    {% block source%}
                    {% include 'source.html'%}
                    {% endblock%}
                </div>
            </div>
            <div class="col-md-10">
                {% block content%}
                {% endblock%}
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

app/templates/category.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}

{% block title%}{{category}}{%endblock%}

{% block content%}

 {{macro.displayNews(category_news)}}
{% endblock%}

app/templates/error.html
{% extends 'base.html'%}

{% block title%}No Results{%endblock%}

{% block content%}
<div class="error text-center">
    <span>No Results<br> Try to search Key Words</span>
</div>
{% endblock%}

app/templates/form.html
<div class="search d-flex justify-content-end m-1">
    <form class="d-flex" method="post">
        {{form.csrf_token}}
        {{form.searchTerm}}
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
</div>

app/templates/home.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
{% block content%}
      {{macro.displayNews(headlinesNews)}}
{% endblock%}

app/templates/macros.html
{% macro displayNews(news_list) %}

    {% for news in news_list %}
    <div class="card">
        <div class="row">
                <div class="col-md-6">              
                <img src="{{news.urlToImage}}" alt="">
                </div>
                <div class="col-md-6 p-2">
                    <a href="{{news.url}}"><h3>{{news.title}}</h3></a>
                    <small><i>Published: {{ news.publishedAt}}</i> </small><br>
                    <blockquote>{{news.description}}</blockquote>
                    <small>Source: {{news.source['name']}}  By {{ news.author}}</small>
                </div>
        </div>
    </div>
    {% endfor%}
{% endmacro%}

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light pt-3 mb-0 sticky-top">
  <div class="container-fluid">
    <a class="navbar-brand text-success" href="#"><b>WHAT's UP NEWS</b></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse d-flex justify-content-center" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{ url_for('views.headline_articles') }}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{  url_for('views.all_News') }}">All News</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{  url_for('views.categoryNews',category = 'business') }}">Business</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{  url_for('views.categoryNews' ,category = 'entertainment') }}">Entertainment</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{  url_for('views.categoryNews',category = 'technology') }}">Technology</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('views.categoryNews',category = 'sports') }}">Sports</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{  url_for('views.categoryNews',category = 'science') }}">Science</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{  url_for('views.categoryNews',category = 'health') }}">Health</a>
        </li>
      </ul>

    </div>
  </div>
</nav>

app/templates/notFound.html
{% extends 'base.html'%}

{% block content%}
<div class="">
    {{error}}
    <h1 class= "text-danger text-center">Whoops! The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</h1>
</div>

{% endblock%}

app/templates/search.html
{% extends 'base.html'%} 
{% import 'macros.html' as macro%}

{% block title%}{{searchTerm}}{%endblock%}
{% block content%}
    {{macro.displayNews(found_news)}}
{%endblock%}

app/templates/source.html
  <div class="list-group ">
    <h2>Sources</h2>
    <a href="{{  url_for('views.channel_News',sourceChannel = 'bbc-news') }}" class="list-group-item list-group-item-action" aria-current="true">
      BBC NEWS
    </a>
    <a href="{{  url_for('views.channel_News',sourceChannel = 'nbc-news') }}" class="list-group-item list-group-item-action">NBC NEWS</a>
    <a href="{{  url_for('views.channel_News',sourceChannel = 'al-jazeera-english') }}" class="list-group-item list-group-item-action">AL JAZEERA</a>
    <a href="{{  url_for('views.channel_News',sourceChannel = 'cnn') }}" class="list-group-item list-group-item-action">CNN NEWS</a>
    <a href="{{  url_for('views.channel_News',sourceChannel = 'fox-news') }}" class="list-group-item list-group-item-action">FOX NEWS</a>
    <a href="{{  url_for('views.channel_News',sourceChannel = 'business-insider') }}" class="list-group-item list-group-item-action">BUSINESS-INSIDER</a>
  </div>